test-name: xntp
uplink-trace: /opt/pantheon/src/experiments/100mbps_datalink.trace
append-mm-cmds: "mm-delay 30"
flows: [
  {"scheme": "xntp"},
  {"scheme": "xntp"},
  {"scheme": "xntp"}
]
runtime: 30
interval: 0

